include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - unnecessary_const
    - unnecessary_new
    - use_super_parameters
    - avoid_dynamic_calls
    - cancel_subscriptions
    - close_sinks
    - public_member_api_docs
    - avoid_slow_async_io

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
