// GENERATED FILE — DO NOT EDIT
// Generated by Sway — To regenerate, run: dart run sway:codegen

part of 'sway.g.dart';

/// ar translations for `app`.
class SwayAppTranslationsAr extends SwayAppTranslations {
  /// Creates [SwayAppTranslationsAr].
  const SwayAppTranslationsAr();

  @override
  /// `سواي`
  String get title => 'سواي';

  @override
  /// `الترجمة لفلاتر`
  String get subtitle => 'الترجمة لفلاتر';

}

/// ar translations for `home`.
class SwayHomeTranslationsAr extends SwayHomeTranslations {
  /// Creates [SwayHomeTranslationsAr].
  const SwayHomeTranslationsAr();

  @override
  /// `أهلاً، {name}!`
  String welcome({required String name}) => 'أهلاً، $name!';

  @override
  /// `اكتب JSON واحصل على Dart آمن بالأنواع، وبدّل اللغة فورًا عبر الزر العائم.`
  String get description => 'اكتب JSON واحصل على Dart آمن بالأنواع، وبدّل اللغة فورًا عبر الزر العائم.';

  @override
  /// `اسحب الزر العائم ثم اضغط لتبديل اللغة أو فرض RTL.`
  String get overlayHint => 'اسحب الزر العائم ثم اضغط لتبديل اللغة أو فرض RTL.';

  @override
  /// Pluralized `itemCount`.
  String itemCount({required num count}) {
    final category = resolvePlural('ar', count);
    switch (category) {
      case PluralCategory.zero: return 'لا عناصر';
      case PluralCategory.one: return 'عنصر واحد';
      case PluralCategory.two: return 'عنصران';
      case PluralCategory.few: return '$count عناصر';
      case PluralCategory.many: return '$count عنصرًا';
      case PluralCategory.other: return '$count عنصر';
    }
  }

  @override
  /// Pluralized `messageCount`.
  String messageCount({required num count}) {
    final category = resolvePlural('ar', count);
    switch (category) {
      case PluralCategory.zero: return 'لا رسائل';
      case PluralCategory.one: return 'رسالة واحدة';
      case PluralCategory.two: return 'رسالتان';
      case PluralCategory.few: return '$count رسائل';
      case PluralCategory.many: return '$count رسالة';
      case PluralCategory.other: return '$count رسالة';
    }
  }

}

/// ar translations for `settings`.
class SwaySettingsTranslationsAr extends SwaySettingsTranslations {
  /// Creates [SwaySettingsTranslationsAr].
  const SwaySettingsTranslationsAr();

  @override
  /// `الإعدادات`
  String get title => 'الإعدادات';

  @override
  /// `اللغة`
  String get language => 'اللغة';

  @override
  /// `الوضع الداكن`
  String get darkMode => 'الوضع الداكن';

  @override
  /// `الإشعارات`
  String get notifications => 'الإشعارات';

  @override
  /// `تسجيل الخروج`
  String get logout => 'تسجيل الخروج';

  @override
  /// `إيقاف`
  String get off => 'إيقاف';

  @override
  /// `تشغيل`
  String get on => 'تشغيل';

}

/// ar translations for `profile`.
class SwayProfileTranslationsAr extends SwayProfileTranslations {
  /// Creates [SwayProfileTranslationsAr].
  const SwayProfileTranslationsAr();

  @override
  /// `الملف الشخصي`
  String get title => 'الملف الشخصي';

  @override
  /// `تعديل الملف الشخصي`
  String get editProfile => 'تعديل الملف الشخصي';

  @override
  /// `الاسم`
  String get name => 'الاسم';

  @override
  /// `البريد الإلكتروني`
  String get email => 'البريد الإلكتروني';

  @override
  /// `عضو منذ {date}`
  String memberSince({required String date}) => 'عضو منذ $date';

}

/// ar translations for `common`.
class SwayCommonTranslationsAr extends SwayCommonTranslations {
  /// Creates [SwayCommonTranslationsAr].
  const SwayCommonTranslationsAr();

  @override
  /// `موافق`
  String get ok => 'موافق';

  @override
  /// `إلغاء`
  String get cancel => 'إلغاء';

  @override
  /// `حفظ`
  String get save => 'حفظ';

  @override
  /// `حذف`
  String get delete => 'حذف';

  @override
  /// `جاري التحميل...`
  String get loading => 'جاري التحميل...';

  @override
  /// `حدث خطأ ما`
  String get error => 'حدث خطأ ما';

  @override
  /// `إعادة المحاولة`
  String get retry => 'إعادة المحاولة';

}

/// Sway translations for locale: ar
class SwayTranslationsAr extends SwayTranslations {
  /// Creates [SwayTranslationsAr].
  const SwayTranslationsAr();

  @override
  Locale get locale => const Locale('ar');

  @override
  bool get isRtl => true;

  @override
  SwayAppTranslationsAr get app => const SwayAppTranslationsAr();

  @override
  SwayHomeTranslationsAr get home => const SwayHomeTranslationsAr();

  @override
  SwaySettingsTranslationsAr get settings => const SwaySettingsTranslationsAr();

  @override
  SwayProfileTranslationsAr get profile => const SwayProfileTranslationsAr();

  @override
  SwayCommonTranslationsAr get common => const SwayCommonTranslationsAr();

}

