// GENERATED FILE — DO NOT EDIT
// Generated by Sway — To regenerate, run: dart run sway:codegen

import 'package:flutter/widgets.dart';

/// Sway translations for locale: ar
class SwayTranslationsAr {
  /// Creates [SwayTranslationsAr].
  const SwayTranslationsAr();

  /// The locale this translations class is for.
  static const Locale locale = Locale('ar');

  /// Whether this locale is right-to-left.
  static const bool isRtl = true;

    /// `عرض سواي`
    String get appTitle => 'عرض سواي';

    /// `الترجمة لفلاتر`
    String get appSubtitle => 'الترجمة لفلاتر';

    /// `!أهلاً {name}`
    String homeWelcome({required String name}) => '!أهلاً $name';

    /// `سواي يجعل ترجمة فلاتر بسيطة. اكتب JSON واحصل على Dart آمن بالأنواع.`
    String get homeDescription => 'سواي يجعل ترجمة فلاتر بسيطة. اكتب JSON واحصل على Dart آمن بالأنواع.';

    /// `لا عناصر`
    String get itemCountZero => 'لا عناصر';

    /// `عنصر واحد`
    String get itemCountOne => 'عنصر واحد';

    /// `عنصران`
    String get itemCountTwo => 'عنصران';

    /// `{count} عناصر`
    String itemCountFew({required num count}) => '$count عناصر';

    /// `{count} عنصرًا`
    String itemCountMany({required num count}) => '$count عنصرًا';

    /// `{count} عنصر`
    String itemCountOther({required num count}) => '$count عنصر';

    /// `لا رسائل`
    String get messageCountZero => 'لا رسائل';

    /// `رسالة واحدة`
    String get messageCountOne => 'رسالة واحدة';

    /// `رسالتان`
    String get messageCountTwo => 'رسالتان';

    /// `{count} رسائل`
    String messageCountFew({required num count}) => '$count رسائل';

    /// `{count} رسالة`
    String messageCountMany({required num count}) => '$count رسالة';

    /// `{count} رسالة`
    String messageCountOther({required num count}) => '$count رسالة';

    /// `الإعدادات`
    String get settingsTitle => 'الإعدادات';

    /// `اللغة`
    String get settingsLanguage => 'اللغة';

    /// `الوضع الداكن`
    String get settingsDarkMode => 'الوضع الداكن';

    /// `الإشعارات`
    String get settingsNotifications => 'الإشعارات';

    /// `تسجيل الخروج`
    String get settingsLogout => 'تسجيل الخروج';

    /// `الملف الشخصي`
    String get profileTitle => 'الملف الشخصي';

    /// `تعديل الملف الشخصي`
    String get profileEditProfile => 'تعديل الملف الشخصي';

    /// `الاسم`
    String get profileName => 'الاسم';

    /// `البريد الإلكتروني`
    String get profileEmail => 'البريد الإلكتروني';

    /// `عضو منذ {date}`
    String profileMemberSince({required String date}) => 'عضو منذ $date';

    /// `موافق`
    String get commonOk => 'موافق';

    /// `إلغاء`
    String get commonCancel => 'إلغاء';

    /// `حفظ`
    String get commonSave => 'حفظ';

    /// `حذف`
    String get commonDelete => 'حذف';

    /// `جاري التحميل...`
    String get commonLoading => 'جاري التحميل...';

    /// `حدث خطأ ما`
    String get commonError => 'حدث خطأ ما';

    /// `إعادة المحاولة`
    String get commonRetry => 'إعادة المحاولة';

}

/// Sway translations for locale: en
class SwayTranslationsEn {
  /// Creates [SwayTranslationsEn].
  const SwayTranslationsEn();

  /// The locale this translations class is for.
  static const Locale locale = Locale('en');

  /// Whether this locale is right-to-left.
  static const bool isRtl = false;

    /// `Sway Demo`
    String get appTitle => 'Sway Demo';

    /// `Localization for Flutter`
    String get appSubtitle => 'Localization for Flutter';

    /// `Welcome, {name}!`
    String homeWelcome({required String name}) => 'Welcome, $name!';

    /// `Sway makes Flutter localization simple. Write JSON, get type-safe Dart.`
    String get homeDescription => 'Sway makes Flutter localization simple. Write JSON, get type-safe Dart.';

    /// `{count} item`
    String itemCountOne({required num count}) => '$count item';

    /// `{count} items`
    String itemCountOther({required num count}) => '$count items';

    /// `{count} message`
    String messageCountOne({required num count}) => '$count message';

    /// `{count} messages`
    String messageCountOther({required num count}) => '$count messages';

    /// `Settings`
    String get settingsTitle => 'Settings';

    /// `Language`
    String get settingsLanguage => 'Language';

    /// `Dark Mode`
    String get settingsDarkMode => 'Dark Mode';

    /// `Notifications`
    String get settingsNotifications => 'Notifications';

    /// `Log out`
    String get settingsLogout => 'Log out';

    /// `Profile`
    String get profileTitle => 'Profile';

    /// `Edit Profile`
    String get profileEditProfile => 'Edit Profile';

    /// `Name`
    String get profileName => 'Name';

    /// `Email`
    String get profileEmail => 'Email';

    /// `Member since {date}`
    String profileMemberSince({required String date}) => 'Member since $date';

    /// `OK`
    String get commonOk => 'OK';

    /// `Cancel`
    String get commonCancel => 'Cancel';

    /// `Save`
    String get commonSave => 'Save';

    /// `Delete`
    String get commonDelete => 'Delete';

    /// `Loading...`
    String get commonLoading => 'Loading...';

    /// `Something went wrong`
    String get commonError => 'Something went wrong';

    /// `Try again`
    String get commonRetry => 'Try again';

}

/// Unified translations registry.
///
/// Access translations via static fields:
/// ```dart
/// final t = SwayTranslations.en;
/// Text(t.appTitle);
/// Text(t.homeWelcome(name: "Dipesh"));
/// ```
class SwayTranslations {
  SwayTranslations._();

  /// Translations for the `ar` locale.
  static const SwayTranslationsAr ar = SwayTranslationsAr();
  /// Translations for the `en` locale.
  static const SwayTranslationsEn en = SwayTranslationsEn();

  /// All supported locales.
  static const List<Locale> supportedLocales = [
    Locale('ar'),
    Locale('en'),
  ];
}
