// GENERATED FILE — DO NOT EDIT
// Generated by Sway — To regenerate, run: dart run sway:codegen

part of 'sway.g.dart';

/// en translations for `app`.
class SwayAppTranslationsEn extends SwayAppTranslations {
  /// Creates [SwayAppTranslationsEn].
  const SwayAppTranslationsEn();

  @override
  /// `Sway`
  String get title => 'Sway';

  @override
  /// `Localization for Flutter`
  String get subtitle => 'Localization for Flutter';

}

/// en translations for `home`.
class SwayHomeTranslationsEn extends SwayHomeTranslations {
  /// Creates [SwayHomeTranslationsEn].
  const SwayHomeTranslationsEn();

  @override
  /// `Welcome, {name}!`
  String welcome({required String name}) => 'Welcome, $name!';

  @override
  /// `Write JSON, get type-safe Dart, and switch locales instantly with the floating button.`
  String get description => 'Write JSON, get type-safe Dart, and switch locales instantly with the floating button.';

  @override
  /// `Drag the floating button, then tap to switch language or force RTL.`
  String get overlayHint => 'Drag the floating button, then tap to switch language or force RTL.';

  @override
  /// Pluralized `itemCount`.
  String itemCount({required num count}) {
    final category = resolvePlural('en', count);
    switch (category) {
      case PluralCategory.one: return '$count item';
      case PluralCategory.other: return '$count items';
      default: return '$count items';
    }
  }

  @override
  /// Pluralized `messageCount`.
  String messageCount({required num count}) {
    final category = resolvePlural('en', count);
    switch (category) {
      case PluralCategory.one: return '$count message';
      case PluralCategory.other: return '$count messages';
      default: return '$count messages';
    }
  }

}

/// en translations for `settings`.
class SwaySettingsTranslationsEn extends SwaySettingsTranslations {
  /// Creates [SwaySettingsTranslationsEn].
  const SwaySettingsTranslationsEn();

  @override
  /// `Settings`
  String get title => 'Settings';

  @override
  /// `Language`
  String get language => 'Language';

  @override
  /// `Dark Mode`
  String get darkMode => 'Dark Mode';

  @override
  /// `Notifications`
  String get notifications => 'Notifications';

  @override
  /// `Log out`
  String get logout => 'Log out';

  @override
  /// `Off`
  String get off => 'Off';

  @override
  /// `On`
  String get on => 'On';

}

/// en translations for `profile`.
class SwayProfileTranslationsEn extends SwayProfileTranslations {
  /// Creates [SwayProfileTranslationsEn].
  const SwayProfileTranslationsEn();

  @override
  /// `Profile`
  String get title => 'Profile';

  @override
  /// `Edit Profile`
  String get editProfile => 'Edit Profile';

  @override
  /// `Name`
  String get name => 'Name';

  @override
  /// `Email`
  String get email => 'Email';

  @override
  /// `Member since {date}`
  String memberSince({required String date}) => 'Member since $date';

}

/// en translations for `common`.
class SwayCommonTranslationsEn extends SwayCommonTranslations {
  /// Creates [SwayCommonTranslationsEn].
  const SwayCommonTranslationsEn();

  @override
  /// `OK`
  String get ok => 'OK';

  @override
  /// `Cancel`
  String get cancel => 'Cancel';

  @override
  /// `Save`
  String get save => 'Save';

  @override
  /// `Delete`
  String get delete => 'Delete';

  @override
  /// `Loading...`
  String get loading => 'Loading...';

  @override
  /// `Something went wrong`
  String get error => 'Something went wrong';

  @override
  /// `Try again`
  String get retry => 'Try again';

}

/// Sway translations for locale: en
class SwayTranslationsEn extends SwayTranslations {
  /// Creates [SwayTranslationsEn].
  const SwayTranslationsEn();

  @override
  Locale get locale => const Locale('en');

  @override
  bool get isRtl => false;

  @override
  SwayAppTranslationsEn get app => const SwayAppTranslationsEn();

  @override
  SwayHomeTranslationsEn get home => const SwayHomeTranslationsEn();

  @override
  SwaySettingsTranslationsEn get settings => const SwaySettingsTranslationsEn();

  @override
  SwayProfileTranslationsEn get profile => const SwayProfileTranslationsEn();

  @override
  SwayCommonTranslationsEn get common => const SwayCommonTranslationsEn();

}

