// GENERATED FILE — DO NOT EDIT
// Generated by Sway — To regenerate, run: dart run sway:codegen

import 'package:flutter/widgets.dart';
import 'package:sway/sway.dart' show PluralCategory, resolvePlural;

part 'sway_ar.g.dart';
part 'sway_de.g.dart';
part 'sway_en.g.dart';
part 'sway_es.g.dart';
part 'sway_he.g.dart';
part 'sway_ja.g.dart';

/// Generated translations for `app`.
abstract class SwayAppTranslations {
  /// Creates a [SwayAppTranslations].
  const SwayAppTranslations();

  /// `Sway`
  String get title;

  /// `Localization for Flutter`
  String get subtitle;
}

/// Generated translations for `home`.
abstract class SwayHomeTranslations {
  /// Creates a [SwayHomeTranslations].
  const SwayHomeTranslations();

  /// `Welcome, {name}!`
  String welcome({required String name});

  /// `Write JSON, get type-safe Dart, and switch locales instantly with the floating button.`
  String get description;

  /// `Drag the floating button, then tap to switch language or force RTL.`
  String get overlayHint;

  /// Pluralized `itemCount`.
  String itemCount({required num count});

  /// Pluralized `messageCount`.
  String messageCount({required num count});
}

/// Generated translations for `settings`.
abstract class SwaySettingsTranslations {
  /// Creates a [SwaySettingsTranslations].
  const SwaySettingsTranslations();

  /// `Settings`
  String get title;

  /// `Language`
  String get language;

  /// `Dark Mode`
  String get darkMode;

  /// `Notifications`
  String get notifications;

  /// `Log out`
  String get logout;

  /// `Off`
  String get off;

  /// `On`
  String get on;
}

/// Generated translations for `profile`.
abstract class SwayProfileTranslations {
  /// Creates a [SwayProfileTranslations].
  const SwayProfileTranslations();

  /// `Profile`
  String get title;

  /// `Edit Profile`
  String get editProfile;

  /// `Name`
  String get name;

  /// `Email`
  String get email;

  /// `Member since {date}`
  String memberSince({required String date});
}

/// Generated translations for `common`.
abstract class SwayCommonTranslations {
  /// Creates a [SwayCommonTranslations].
  const SwayCommonTranslations();

  /// `OK`
  String get ok;

  /// `Cancel`
  String get cancel;

  /// `Save`
  String get save;

  /// `Delete`
  String get delete;

  /// `Loading...`
  String get loading;

  /// `Something went wrong`
  String get error;

  /// `Try again`
  String get retry;
}

/// Root generated translations interface.
abstract class SwayTranslations {
  /// Creates [SwayTranslations].
  const SwayTranslations();

  /// Locale of this translations instance.
  Locale get locale;

  /// Whether this locale is right-to-left.
  bool get isRtl;

  /// Nested `app` translations.
  SwayAppTranslations get app;

  /// Nested `home` translations.
  SwayHomeTranslations get home;

  /// Nested `settings` translations.
  SwaySettingsTranslations get settings;

  /// Nested `profile` translations.
  SwayProfileTranslations get profile;

  /// Nested `common` translations.
  SwayCommonTranslations get common;

  /// Translations for `ar`.
  static SwayTranslations get ar => const SwayTranslationsAr();

  /// Translations for `de`.
  static SwayTranslations get de => const SwayTranslationsDe();

  /// Translations for `en`.
  static SwayTranslations get en => const SwayTranslationsEn();

  /// Translations for `es`.
  static SwayTranslations get es => const SwayTranslationsEs();

  /// Translations for `he`.
  static SwayTranslations get he => const SwayTranslationsHe();

  /// Translations for `ja`.
  static SwayTranslations get ja => const SwayTranslationsJa();

  /// All supported locales.
  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('ar'),
    Locale('de'),
    Locale('es'),
    Locale('he'),
    Locale('ja'),
  ];

  /// Longhand: translations for [locale], falling back to `en`.
  static SwayTranslations forLocale(Locale locale) {
    switch (locale.languageCode) {
      case 'ar':
        return ar;
      case 'de':
        return de;
      case 'en':
        return en;
      case 'es':
        return es;
      case 'he':
        return he;
      case 'ja':
        return ja;
      default:
        return en;
    }
  }

  /// Flutter-style lookup from the nearest [SwayScope].
  ///
  /// Prefer shorthand: `context.t.home.welcome(name: …)`.
  static SwayTranslations of(BuildContext context) => SwayScope.of(context);
}

/// Provides [SwayTranslations] to descendants (like `Localizations`).
class SwayScope extends InheritedWidget {
  /// Active translations for this subtree.
  final SwayTranslations translations;

  /// Creates a [SwayScope].
  const SwayScope({
    super.key,
    required this.translations,
    required super.child,
  });

  /// Looks up translations from [context].
  static SwayTranslations of(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<SwayScope>();
    assert(
      scope != null,
      'No SwayScope found. Wrap your app with SwayScope(translations: SwayTranslations.forLocale(locale), child: …).',
    );
    return scope!.translations;
  }

  /// Same as [of], but returns null if missing.
  static SwayTranslations? maybeOf(BuildContext context) {
    return context
        .dependOnInheritedWidgetOfExactType<SwayScope>()
        ?.translations;
  }

  @override
  bool updateShouldNotify(SwayScope oldWidget) =>
      translations.locale != oldWidget.translations.locale ||
      !identical(translations, oldWidget.translations);
}

/// Shorthand accessors for generated translations.
extension SwayTranslationsX on BuildContext {
  /// Shorthand: `context.t.home.welcome(name: 'Dipesh')`.
  SwayTranslations get t => SwayTranslations.of(this);

  /// Longhand alias of [t].
  SwayTranslations get sway => SwayTranslations.of(this);
}
