// GENERATED FILE — DO NOT EDIT
// Generated by Sway — To regenerate, run: dart run sway:codegen

part of 'sway.g.dart';

/// de translations for `app`.
class SwayAppTranslationsDe extends SwayAppTranslations {
  /// Creates [SwayAppTranslationsDe].
  const SwayAppTranslationsDe();

  @override

  /// `Sway`
  String get title => 'Sway';

  @override

  /// `Lokalisierung für Flutter`
  String get subtitle => 'Lokalisierung für Flutter';
}

/// de translations for `home`.
class SwayHomeTranslationsDe extends SwayHomeTranslations {
  /// Creates [SwayHomeTranslationsDe].
  const SwayHomeTranslationsDe();

  @override

  /// `Willkommen, {name}!`
  String welcome({required String name}) => 'Willkommen, $name!';

  @override

  /// `JSON schreiben, typsicheres Dart erhalten und Sprache sofort über den schwebenden Button wechseln.`
  String get description =>
      'JSON schreiben, typsicheres Dart erhalten und Sprache sofort über den schwebenden Button wechseln.';

  @override

  /// `Ziehen Sie den schwebenden Button und tippen Sie, um Sprache zu wechseln oder RTL zu erzwingen.`
  String get overlayHint =>
      'Ziehen Sie den schwebenden Button und tippen Sie, um Sprache zu wechseln oder RTL zu erzwingen.';

  @override

  /// Pluralized `itemCount`.
  String itemCount({required num count}) {
    final category = resolvePlural('de', count);
    switch (category) {
      case PluralCategory.one:
        return '$count Element';
      case PluralCategory.other:
        return '$count Elemente';
      default:
        return '$count Elemente';
    }
  }

  @override

  /// Pluralized `messageCount`.
  String messageCount({required num count}) {
    final category = resolvePlural('de', count);
    switch (category) {
      case PluralCategory.one:
        return '$count Nachricht';
      case PluralCategory.other:
        return '$count Nachrichten';
      default:
        return '$count Nachrichten';
    }
  }
}

/// de translations for `settings`.
class SwaySettingsTranslationsDe extends SwaySettingsTranslations {
  /// Creates [SwaySettingsTranslationsDe].
  const SwaySettingsTranslationsDe();

  @override

  /// `Einstellungen`
  String get title => 'Einstellungen';

  @override

  /// `Sprache`
  String get language => 'Sprache';

  @override

  /// `Dunkelmodus`
  String get darkMode => 'Dunkelmodus';

  @override

  /// `Benachrichtigungen`
  String get notifications => 'Benachrichtigungen';

  @override

  /// `Abmelden`
  String get logout => 'Abmelden';

  @override

  /// `Aus`
  String get off => 'Aus';

  @override

  /// `An`
  String get on => 'An';
}

/// de translations for `profile`.
class SwayProfileTranslationsDe extends SwayProfileTranslations {
  /// Creates [SwayProfileTranslationsDe].
  const SwayProfileTranslationsDe();

  @override

  /// `Profil`
  String get title => 'Profil';

  @override

  /// `Profil bearbeiten`
  String get editProfile => 'Profil bearbeiten';

  @override

  /// `Name`
  String get name => 'Name';

  @override

  /// `E-Mail`
  String get email => 'E-Mail';

  @override

  /// `Mitglied seit {date}`
  String memberSince({required String date}) => 'Mitglied seit $date';
}

/// de translations for `common`.
class SwayCommonTranslationsDe extends SwayCommonTranslations {
  /// Creates [SwayCommonTranslationsDe].
  const SwayCommonTranslationsDe();

  @override

  /// `OK`
  String get ok => 'OK';

  @override

  /// `Abbrechen`
  String get cancel => 'Abbrechen';

  @override

  /// `Speichern`
  String get save => 'Speichern';

  @override

  /// `Löschen`
  String get delete => 'Löschen';

  @override

  /// `Laden...`
  String get loading => 'Laden...';

  @override

  /// `Etwas ist schiefgelaufen`
  String get error => 'Etwas ist schiefgelaufen';

  @override

  /// `Erneut versuchen`
  String get retry => 'Erneut versuchen';
}

/// Sway translations for locale: de
class SwayTranslationsDe extends SwayTranslations {
  /// Creates [SwayTranslationsDe].
  const SwayTranslationsDe();

  @override
  Locale get locale => const Locale('de');

  @override
  bool get isRtl => false;

  @override
  SwayAppTranslationsDe get app => const SwayAppTranslationsDe();

  @override
  SwayHomeTranslationsDe get home => const SwayHomeTranslationsDe();

  @override
  SwaySettingsTranslationsDe get settings => const SwaySettingsTranslationsDe();

  @override
  SwayProfileTranslationsDe get profile => const SwayProfileTranslationsDe();

  @override
  SwayCommonTranslationsDe get common => const SwayCommonTranslationsDe();
}
