/// Nested Dart emitter for Sway locale files.
///
/// Emits one main library (`sway.g.dart`) plus one `part` file per locale
/// (`sway_en.g.dart`, `sway_ar.g.dart`, …) — same shape as Flutter gen-l10n.
library;

import 'package:path/path.dart' as p;

import '../format/locale_file.dart';
import '../format/rtl_table.dart';
import 'config.dart';

const _pluralCategories = {'zero', 'one', 'two', 'few', 'many', 'other'};

/// Result of a multi-file codegen emit.
class SwayEmitResult {
  /// Basename → source (e.g. `sway.g.dart`, `sway_en.g.dart`).
  final Map<String, String> files;

  /// Creates a [SwayEmitResult].
  const SwayEmitResult(this.files);
}

/// Generates type-safe nested Dart from parsed locale files.
class SwayEmitter {
  /// Emits a main library + one part file per locale.
  ///
  /// Keys are basenames relative to the output directory of [config.outputFile].
  static SwayEmitResult emit(
    List<ParsedLocaleFile> localeFiles, {
    required SwayConfig config,
  }) {
    if (localeFiles.isEmpty) {
      throw StateError('No locale files to emit');
    }

    final sorted = [...localeFiles]
      ..sort((a, b) => a.languageCode.compareTo(b.languageCode));

    final base = sorted.firstWhere(
      (f) => f.languageCode == config.baseLocale,
      orElse: () => sorted.first,
    );

    final mainName = p.basename(config.outputFile);
    final stem = _stem(mainName); // "sway" from "sway.g.dart"

    final files = <String, String>{};
    final partNames = <String>[];

    for (final file in sorted) {
      final partName = '${stem}_${file.languageCode}.g.dart';
      partNames.add(partName);
      final partBuf = StringBuffer();
      partBuf.writeln('// GENERATED FILE — DO NOT EDIT');
      partBuf.writeln(
        '// Generated by Sway — To regenerate, run: dart run sway:codegen',
      );
      partBuf.writeln();
      partBuf.writeln("part of '$mainName';");
      partBuf.writeln();
      _emitLocaleImpl(partBuf, file, base, config);
      files[partName] = partBuf.toString();
    }

    final mainBuf = StringBuffer();
    mainBuf.writeln('// GENERATED FILE — DO NOT EDIT');
    mainBuf.writeln(
      '// Generated by Sway — To regenerate, run: dart run sway:codegen',
    );
    mainBuf.writeln();
    mainBuf.writeln("import 'package:flutter/widgets.dart';");
    mainBuf.writeln(
      "import 'package:sway/sway.dart' show PluralCategory, resolvePlural;",
    );
    mainBuf.writeln();
    for (final partName in partNames) {
      mainBuf.writeln("part '$partName';");
    }
    mainBuf.writeln();

    _emitNestedAbstracts(mainBuf, base.data, '');
    _emitRootAbstract(mainBuf, base, sorted);

    files[mainName] = mainBuf.toString();
    return SwayEmitResult(files);
  }

  /// `sway.g.dart` → `sway`, `app_localizations.dart` → `app_localizations`.
  static String _stem(String basename) {
    if (basename.endsWith('.g.dart')) {
      return basename.substring(0, basename.length - '.g.dart'.length);
    }
    if (basename.endsWith('.dart')) {
      return basename.substring(0, basename.length - '.dart'.length);
    }
    return basename;
  }

  static void _emitNestedAbstracts(
    StringBuffer buffer,
    Map<String, dynamic> data,
    String pathPrefix,
  ) {
    for (final entry in data.entries) {
      if (entry.value is! Map<String, dynamic>) continue;
      final sub = entry.value as Map<String, dynamic>;
      if (_isPlural(sub)) continue;
      final childPath =
          pathPrefix.isEmpty ? entry.key : '$pathPrefix.${entry.key}';
      _emitNestedAbstracts(buffer, sub, childPath);
      _emitNamespaceAbstract(buffer, sub, childPath);
    }
  }

  static void _emitNamespaceAbstract(
    StringBuffer buffer,
    Map<String, dynamic> data,
    String pathPrefix,
  ) {
    final className = _namespaceClass(pathPrefix);
    buffer.writeln('/// Generated translations for `$pathPrefix`.');
    buffer.writeln('abstract class $className {');
    buffer.writeln('  /// Creates a [$className].');
    buffer.writeln('  const $className();');
    buffer.writeln();
    _emitAbstractMembers(buffer, data, pathPrefix);
    buffer.writeln('}');
    buffer.writeln();
  }

  static void _emitRootAbstract(
    StringBuffer buffer,
    ParsedLocaleFile base,
    List<ParsedLocaleFile> all,
  ) {
    buffer.writeln('/// Root generated translations interface.');
    buffer.writeln('abstract class SwayTranslations {');
    buffer.writeln('  /// Creates [SwayTranslations].');
    buffer.writeln('  const SwayTranslations();');
    buffer.writeln();
    buffer.writeln('  /// Locale of this translations instance.');
    buffer.writeln('  Locale get locale;');
    buffer.writeln();
    buffer.writeln('  /// Whether this locale is right-to-left.');
    buffer.writeln('  bool get isRtl;');
    buffer.writeln();
    _emitAbstractMembers(buffer, base.data, '');

    for (final file in all) {
      final code = file.languageCode;
      final suffix = _toSuffix(code);
      buffer.writeln('  /// Translations for `$code`.');
      buffer.writeln(
        '  static SwayTranslations get $code => const SwayTranslations$suffix();',
      );
      buffer.writeln();
    }

    buffer.writeln('  /// All supported locales.');
    buffer.writeln('  static const List<Locale> supportedLocales = [');
    final ordered = [
      base,
      ...all.where((f) => f.languageCode != base.languageCode),
    ];
    for (final file in ordered) {
      buffer.writeln("    Locale('${file.languageCode}'),");
    }
    buffer.writeln('  ];');
    buffer.writeln();
    buffer.writeln(
      '  /// Returns translations for [locale], falling back to `${base.languageCode}`.',
    );
    buffer.writeln('  static SwayTranslations of(Locale locale) {');
    buffer.writeln('    switch (locale.languageCode) {');
    for (final file in all) {
      buffer.writeln(
        "      case '${file.languageCode}': return ${file.languageCode};",
      );
    }
    buffer.writeln('      default: return ${base.languageCode};');
    buffer.writeln('    }');
    buffer.writeln('  }');
    buffer.writeln('}');
  }

  static void _emitAbstractMembers(
    StringBuffer buffer,
    Map<String, dynamic> data,
    String pathPrefix,
  ) {
    for (final entry in data.entries) {
      final key = entry.key;
      if (entry.value is String) {
        _emitAbstractString(buffer, key, entry.value as String);
      } else if (entry.value is Map<String, dynamic>) {
        final sub = entry.value as Map<String, dynamic>;
        if (_isPlural(sub)) {
          _emitAbstractPlural(buffer, key, sub);
        } else {
          final childPath =
              pathPrefix.isEmpty ? key : '$pathPrefix.$key';
          buffer.writeln('  /// Nested `$key` translations.');
          buffer.writeln('  ${_namespaceClass(childPath)} get $key;');
          buffer.writeln();
        }
      }
    }
  }

  static void _emitAbstractString(
    StringBuffer buffer,
    String key,
    String value,
  ) {
    final placeholders = _placeholders(value);
    if (placeholders.isEmpty) {
      buffer.writeln('  /// `$value`');
      buffer.writeln('  String get $key;');
    } else {
      buffer.writeln('  /// `$value`');
      buffer.writeln('  String $key({${_paramList(placeholders)}});');
    }
    buffer.writeln();
  }

  static void _emitAbstractPlural(
    StringBuffer buffer,
    String key,
    Map<String, dynamic> plural,
  ) {
    final placeholders = <String>{'count'};
    for (final v in plural.values) {
      if (v is String) placeholders.addAll(_placeholders(v));
    }
    buffer.writeln('  /// Pluralized `$key`.');
    buffer.writeln('  String $key({${_paramList(placeholders)}});');
    buffer.writeln();
  }

  static void _emitLocaleImpl(
    StringBuffer buffer,
    ParsedLocaleFile file,
    ParsedLocaleFile base,
    SwayConfig config,
  ) {
    final suffix = _toSuffix(file.languageCode);
    final isRtl = isRtlLanguage(file.languageCode);

    _emitImplTree(
      buffer,
      file,
      config,
      file.data,
      base.data,
      '',
      suffix,
    );

    buffer.writeln('/// Sway translations for locale: ${file.languageCode}');
    buffer.writeln('class SwayTranslations$suffix extends SwayTranslations {');
    buffer.writeln('  /// Creates [SwayTranslations$suffix].');
    buffer.writeln('  const SwayTranslations$suffix();');
    buffer.writeln();
    buffer.writeln('  @override');
    buffer.writeln(
      "  Locale get locale => const Locale('${file.languageCode}');",
    );
    buffer.writeln();
    buffer.writeln('  @override');
    buffer.writeln('  bool get isRtl => $isRtl;');
    buffer.writeln();

    _emitImplMembers(
      buffer,
      file,
      config,
      file.data,
      base.data,
      '',
      suffix,
    );

    buffer.writeln('}');
    buffer.writeln();
  }

  static void _emitImplTree(
    StringBuffer buffer,
    ParsedLocaleFile file,
    SwayConfig config,
    Map<String, dynamic> data,
    Map<String, dynamic> baseData,
    String pathPrefix,
    String localeSuffix,
  ) {
    for (final entry in baseData.entries) {
      if (entry.value is! Map<String, dynamic>) continue;
      final baseSub = entry.value as Map<String, dynamic>;
      if (_isPlural(baseSub)) continue;

      final key = entry.key;
      final childPath =
          pathPrefix.isEmpty ? key : '$pathPrefix.$key';
      final fileSub = data[key] is Map<String, dynamic>
          ? data[key] as Map<String, dynamic>
          : <String, dynamic>{};

      _emitImplTree(
        buffer,
        file,
        config,
        fileSub,
        baseSub,
        childPath,
        localeSuffix,
      );

      final className =
          'Sway${_pathToSuffix(childPath)}Translations$localeSuffix';
      final abstractName = _namespaceClass(childPath);

      buffer.writeln('/// ${file.languageCode} translations for `$childPath`.');
      buffer.writeln('class $className extends $abstractName {');
      buffer.writeln('  /// Creates [$className].');
      buffer.writeln('  const $className();');
      buffer.writeln();

      _emitImplMembers(
        buffer,
        file,
        config,
        fileSub,
        baseSub,
        childPath,
        localeSuffix,
      );

      buffer.writeln('}');
      buffer.writeln();
    }
  }

  static void _emitImplMembers(
    StringBuffer buffer,
    ParsedLocaleFile file,
    SwayConfig config,
    Map<String, dynamic> data,
    Map<String, dynamic> baseData,
    String pathPrefix,
    String localeSuffix,
  ) {
    for (final entry in baseData.entries) {
      final key = entry.key;
      final value = data[key] ?? entry.value;
      if (entry.value is String) {
        final str = value is String
            ? value
            : (config.fallbackStrategy == 'key'
                ? (pathPrefix.isEmpty ? key : '$pathPrefix.$key')
                : entry.value as String);
        _emitImplString(buffer, key, str);
      } else if (entry.value is Map<String, dynamic>) {
        final baseSub = entry.value as Map<String, dynamic>;
        if (_isPlural(baseSub)) {
          final plural = value is Map<String, dynamic> && _isPlural(value)
              ? value
              : baseSub;
          _emitImplPlural(buffer, key, plural, file.languageCode);
        } else {
          final childPath =
              pathPrefix.isEmpty ? key : '$pathPrefix.$key';
          final nestedClass =
              'Sway${_pathToSuffix(childPath)}Translations$localeSuffix';
          buffer.writeln('  @override');
          buffer.writeln('  $nestedClass get $key => const $nestedClass();');
          buffer.writeln();
        }
      }
    }
  }

  static void _emitImplString(
    StringBuffer buffer,
    String key,
    String value,
  ) {
    final placeholders = _placeholders(value);
    buffer.writeln('  @override');
    if (placeholders.isEmpty) {
      buffer.writeln('  /// `$value`');
      buffer.writeln("  String get $key => '${_escape(value)}';");
    } else {
      buffer.writeln('  /// `$value`');
      buffer.writeln(
        "  String $key({${_paramList(placeholders)}}) => '${_interpolate(value, placeholders)}';",
      );
    }
    buffer.writeln();
  }

  static void _emitImplPlural(
    StringBuffer buffer,
    String key,
    Map<String, dynamic> plural,
    String languageCode,
  ) {
    final placeholders = <String>{'count'};
    for (final v in plural.values) {
      if (v is String) placeholders.addAll(_placeholders(v));
    }

    buffer.writeln('  @override');
    buffer.writeln('  /// Pluralized `$key`.');
    buffer.writeln('  String $key({${_paramList(placeholders)}}) {');
    buffer.writeln(
      "    final category = resolvePlural('$languageCode', count);",
    );
    buffer.writeln('    switch (category) {');
    for (final cat in _pluralCategories) {
      if (!plural.containsKey(cat)) continue;
      final raw = plural[cat] as String;
      buffer.writeln(
        "      case PluralCategory.$cat: return '${_interpolate(raw, placeholders)}';",
      );
    }
    final fallback =
        plural['other'] as String? ?? plural.values.cast<String>().first;
    if (plural.keys.length < _pluralCategories.length) {
      buffer.writeln(
        "      default: return '${_interpolate(fallback, placeholders)}';",
      );
    }
    buffer.writeln('    }');
    buffer.writeln('  }');
    buffer.writeln();
  }

  static String _interpolate(String value, Set<String> placeholders) {
    var out = _escape(value);
    for (final name in placeholders) {
      out = out.replaceAll('{$name}', '\$$name');
    }
    return out;
  }

  static String _namespaceClass(String pathPrefix) =>
      'Sway${_pathToSuffix(pathPrefix)}Translations';

  static String _pathToSuffix(String path) {
    return path
        .split('.')
        .where((p) => p.isNotEmpty)
        .map((p) => '${p[0].toUpperCase()}${p.substring(1)}')
        .join();
  }

  static String _toSuffix(String langCode) {
    return langCode
        .split('_')
        .map((p) => '${p[0].toUpperCase()}${p.substring(1)}')
        .join();
  }

  static bool _isPlural(Map<String, dynamic> value) {
    if (value.isEmpty) return false;
    return value.keys.every(_pluralCategories.contains);
  }

  static Set<String> _placeholders(String value) {
    return RegExp(r'\{(\w+)\}')
        .allMatches(value)
        .map((m) => m.group(1)!)
        .toSet();
  }

  static String _paramList(Set<String> placeholders) {
    final sorted = placeholders.toList()
      ..sort((a, b) {
        if (a == 'count') return -1;
        if (b == 'count') return 1;
        return a.compareTo(b);
      });
    return sorted.map((name) {
      final type = name == 'count' ? 'num' : 'String';
      return 'required $type $name';
    }).join(', ');
  }

  static String _escape(String s) {
    return s
        .replaceAll('\\', '\\\\')
        .replaceAll("'", "\\'")
        .replaceAll('\$', '\\\$')
        .replaceAll('\n', '\\n')
        .replaceAll('\r', '\\r')
        .replaceAll('\t', '\\t');
  }
}
